attention_head_size: 4
categorical_groups: {}
causal_attention: true
dataset_parameters: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes:
  dummy: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 64
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 2
mask_bias: -1000000000.0
max_encoder_length: 10
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 1
output_transformer: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder: []
weight_decay: 0.0
x_categoricals:
- dummy
x_reals:
- log_chl
- Kd_490
- nflh
- u10
- v10
- wind_speed
- tau_mag
- avg_sdswrf
- tp
- t2m
- d2m
- uo
- vo
- cur_speed
- cur_div
- cur_vort
- zos
- ssh_grad_mag
- so
- thetao
- chl_anom_monthly
- chl_roll24d_mean
- chl_roll24d_std
- chl_roll40d_mean
- chl_roll40d_std
- river_rank
- dist_river_km
- ocean_mask_static
- river_rank
- dist_river_km
- ocean_mask_static
