// Generate TypeScript types from the pipeline's JSON Schema (schemas/v1).
// The Pydantic models in pipeline/coastwatch_pipeline/models.py are the source of truth.
import { compile } from "json-schema-to-typescript";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = join(root, "..", "schemas", "v1");

export async function generate() {
  let out =
    "// AUTO-GENERATED by scripts/gen-types.mjs from schemas/v1. Do not edit.\n\n";
  const seen = new Set();
  for (const name of ["manifest", "ports"]) {
    const schema = JSON.parse(readFileSync(join(schemaDir, `${name}.schema.json`), "utf8"));
    const ts = await compile(schema, schema.title, {
      bannerComment: "",
      additionalProperties: false,
      unreachableDefinitions: false,
      style: { semi: true, singleQuote: false },
    });
    // Both schemas share definitions (e.g. Provenance); drop duplicate declarations.
    const blocks = ts.split(/\n(?=export )/);
    for (const b of blocks) {
      const m = b.match(/^export (?:interface|type) (\w+)/);
      if (m && seen.has(m[1])) continue;
      if (m) seen.add(m[1]);
      out += b.trim() + "\n\n";
    }
  }
  return out.trimEnd() + "\n";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = await generate();
  writeFileSync(join(root, "src", "generated", "schema.ts"), out);
  // Copy the schemas so the server can validate artifacts at runtime.
  mkdirSync(join(root, "src", "generated", "schemas"), { recursive: true });
  for (const name of ["manifest", "ports"]) {
    copyFileSync(join(schemaDir, `${name}.schema.json`), join(root, "src", "generated", "schemas", `${name}.schema.json`));
  }
  console.log("wrote src/generated/schema.ts and src/generated/schemas/*.json");
}
